# Site settings
title: London Data Week
email: londondataweek@gmail.com
url: https://londondataweek.github.io
description: "London Data Week centres residents in conversations, exhibits, and interactive events about data. Join us July 3-9 2023 in London!"
keywords: "data, technology, london"
skills: "Join us July 3-9 2023!"
meta_author: London Data Week

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C3D2D9
  primary-rgb: "24,288,156"
  secondary: 2c3e50 
  secondary-dark: 11181f 

# Footer settings
footer:
  copyright: London Data Week
  location: London, UK
  social: Around the Web
  credits: LDW Partners

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: instagram
    url:
  - title: github
    url: 

# Credits
credits: TBA in January 2023

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
