# Site settings
title: LDW23
email: londondataweek@gmail.com
url: https://londondataweek.github.io
description: "London Data Week centres residents in conversations, exhibits, and interactive events about data. Join us July 3-9 2023 in London!"
keywords: "data, technology, london"
skills: "Join us July 3-9 2023!"
meta_author: London Data Week

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 11181f #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: London Data Week
  location: London, UK
  social: Around the Web
  credits: LDW Partners

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LOTI_LDN
  - title: instagram
    url:
  - title: github
    url: https://github.com/londondataweek

# Credits
credits: TBA in January 2023

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
